### ISSUE TITLE
Price summary should show mid price

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/dex-explorer#161]
See for example

![image](https://github.com/user-attachments/assets/e22b9a7f-6d84-4134-8872-3dfacc08dfee)

![image](https://github.com/user-attachments/assets/a77edcb7-473f-4f2e-9c05-04e15ab74d9b)

The price shown in the summary should be the mid price. Penumbras DEX guarantees this is consistent with all other trades and prices on the DEX at the end of every block.

**todo: change wording of price in summary to last price**

**Comment by vacekj** [comment]
Note: escalate to lucas if not clear

**Comment by cronokirby** [comment]
Right now, the prices in the summary (both now, and in the past, to create the 24h change) are driven by the candlestick chart. The reason behind this was that in indexing, you can't simulate the route book completely without being able to run the entire Dex to emulate routing, thus having a midpoint price at every point in time is much harder compared to having a slightly backwards looking execution price. Using this price is also consistent with the chart, and everywhere else indexing needs a price, like turning values in one denom into another.

Because of this, even just copying the midpoint in the route book over doesn't fix the issue per se, in that there will still be a discrepancy between the summary price and the chart itself, or more harder to notice ones like, e.g. if the price is flat, there nonetheless being a difference between the price now and 24h ago, and other things like that.

As far as why this might occur (not ruling out a potential bug though), I can think of two scenarios which can lead to this:
1. Trades and Arb having large price impact:
Because the execution price looks at when an actual trade happened, if a large amount of liquidity positions are closed through a trade, then the resulting route book can have a different price if there's a large gap between the closed positions and the new positions. As an extreme case, consider there being just two positions which have a crossover, in which case arb might wipe them out, and then the midpoint price will no longer exist, but the execution price will be whatever arb got out of crossing over the positions.

2. Persistent spread without trade volume
If you just open positions on a pair with a spread between the buy and sell side, and no one actually attempts to trade on the pair directly, then you'd expect the midpoint to start diverging from the execution price. Arb will not force through an execution as long as there's not a cross over in the route book, because it's not profitable to go through the spread, so as long as no trades happen, you would not expect the execution price to change, but the midpoint price may very well change.

Because of this, I think we shouldn't just copy the midpoint price in the routebook, because this makes the summary consistent with the chart, and the price 24h ago, and other places driven by or using prices.

**Comment by cronokirby** [comment]
![image](https://github.com/user-attachments/assets/930e27b9-48cb-4fd0-8d2f-2e85461f3213)
e.g. right now on this pair, there's only 2 direct lps on one side of the route, so any movement in the mid price is being driven by what's happening on other pairs, but because the lps are on one side on this pair directly, this doesn't result in arb, so the last execution price is different from the purported midpoint price.
